export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_OTP = 'INVALID_OTP',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  WRONG_CURRENT_PASSWORD = 'WRONG_CURRENT_PASSWORD',

  // Category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_PARENT_CATEGORY = 'INVALID_PARENT_CATEGORY',
  CIRCULAR_CATEGORY_REFERENCE = 'CIRCULAR_CATEGORY_REFERENCE',
  CATEGORY_TYPE_MISMATCH = 'CATEGORY_TYPE_MISMATCH',
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',

  // Transaction
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_CATEGORY_TYPE_MISMATCH = 'TRANSACTION_CATEGORY_TYPE_MISMATCH',
  SAME_WALLET_TRANSFER = 'SAME_WALLET_TRANSFER',
}
