export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  HEALTH_CHECK_FAILED = 'HEALTH_CHECK_FAILED',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_OTP = 'INVALID_OTP',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  WRONG_CURRENT_PASSWORD = 'WRONG_CURRENT_PASSWORD',

  // Category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_PARENT_CATEGORY = 'INVALID_PARENT_CATEGORY',
  CIRCULAR_CATEGORY_REFERENCE = 'CIRCULAR_CATEGORY_REFERENCE',
  CATEGORY_TYPE_MISMATCH = 'CATEGORY_TYPE_MISMATCH',
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',

  // Transaction
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_CATEGORY_TYPE_MISMATCH = 'TRANSACTION_CATEGORY_TYPE_MISMATCH',
  SAME_WALLET_TRANSFER = 'SAME_WALLET_TRANSFER',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',

  // Budget
  BUDGET_NOT_FOUND = 'BUDGET_NOT_FOUND',
  BUDGET_PERIOD_OVERLAP = 'BUDGET_PERIOD_OVERLAP',

  // Goal
  GOAL_NOT_FOUND = 'GOAL_NOT_FOUND',
  GOAL_ALREADY_FINISHED = 'GOAL_ALREADY_FINISHED',
  GOAL_TARGET_LESS_THAN_CURRENT = 'GOAL_TARGET_LESS_THAN_CURRENT',

  // Report
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
}
